Release 2020.1 Beta Update 9

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -14,18 +14,18 @@ build_dir=${proj_dir}/_extbuild
 DEFAULT_VPL_BUILD_DEPENDENCIES=${proj_dir}/_deps
 
 if [ -z "$VPL_BUILD_DEPENDENCIES" ];then
-    # make sure VPL_BUILD_DEPENDENCIES will be available after script is run
-    if [ "${BASH_SOURCE[0]}" == "${0}" ];then
-        msg="VPL_BUILD_DEPENDENCIES is not set in the environment and the \
+  # make sure VPL_BUILD_DEPENDENCIES will be available after script is run
+  if [ "${BASH_SOURCE[0]}" == "${0}" ];then
+      msg="VPL_BUILD_DEPENDENCIES is not set in the environment and the \
 script is not being sourced. Export VPL_BUILD_DEPENDENCIES or call like this:"
-        printf "%s\n\nsource %s\n" "$msg" "$BASH_SOURCE" | fold -s
-        exit 1
-    fi
-    export VPL_BUILD_DEPENDENCIES="${DEFAULT_VPL_BUILD_DEPENDENCIES}"
+      printf "%s\n\nsource %s\n" "$msg" "$BASH_SOURCE" | fold -s
+      exit 1
+  fi
+  export VPL_BUILD_DEPENDENCIES="${DEFAULT_VPL_BUILD_DEPENDENCIES}"
 fi
 if [ "${BASH_SOURCE[0]}" == "${0}" ];then
-    #exit on error if we are not sourced
-    set -o errexit
+  #exit on error if we are not sourced
+  set -o errexit
 fi
 
 install_dir=${VPL_BUILD_DEPENDENCIES}
@@ -36,15 +36,13 @@ rm -rf ${VPL_BUILD_DEPENDENCIES}
 ## build FFmpeg with SVT-HEVC
 mkdir -p ${build_dir}
 cd ${build_dir}
-git clone https://github.com/OpenVisualCloud/SVT-HEVC.git && cd SVT-HEVC
-git config advice.detachedHead false
-git checkout v1.4.3
+git clone --depth=1 --single-branch -b v1.4.3 https://github.com/OpenVisualCloud/SVT-HEVC.git && cd SVT-HEVC
 sed -i 's/#define LIB_PRINTF_ENABLE                1/#define LIB_PRINTF_ENABLE                0/' \
       ./Source/Lib/Codec/EbDefinitions.h
 mkdir release && cd release
 cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_PREFIX=${install_dir}/ -DBUILD_SHARED_LIBS=off -DBUILD_APP=off
-cmake --build . --target install
+make -j $(nproc) && make install
 
 cd ${build_dir}
 git clone https://github.com/OpenVisualCloud/SVT-AV1.git && cd SVT-AV1
@@ -56,20 +54,26 @@ git checkout c40ee249286f182f29bab717686c300e2912adfe -b 06112020
 mkdir release && cd release
 cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_PREFIX=${install_dir}/ -DBUILD_SHARED_LIBS=off -DBUILD_APPS=off -DCMAKE_C_FLAGS="$(CMAKE_C_FLAGS) -DSVT_LOG_QUIET=1"
-cmake --build . --target install
+make -j $(nproc) && make install
+
+if [ "$1" == "gpl" ]; then
+  ## build x264
+  cd ${build_dir}
+  git clone --depth 1 https://code.videolan.org/videolan/x264.git && cd x264
+  ./configure --prefix=${install_dir} --enable-static --enable-pic
+  PATH="${install_dir}/bin:$PATH" && PKG_CONFIG_PATH="${install_dir}/lib/pkgconfig"
+  make && make install
+fi
 
 ## build libdav1d
 cd ${build_dir}
-git clone https://code.videolan.org/videolan/dav1d.git && cd dav1d
-git config advice.detachedHead false
-git checkout 0.7.0
+git clone --depth=1 --single-branch -b0.7.0  https://code.videolan.org/videolan/dav1d.git && cd dav1d
 meson build --prefix ${install_dir}/ --libdir ${install_dir}/lib --buildtype release --default-library=static -Denable_avx512=false
 ninja -C build && cd build
 ninja install
 
 cd ${build_dir}
-git clone https://github.com/FFmpeg/FFmpeg ffmpeg && cd ffmpeg
-git checkout release/4.2
+git clone --depth=1 --single-branch -b release/4.2 https://github.com/FFmpeg/FFmpeg ffmpeg && cd ffmpeg
 
 git config user.email "bootstrap@localhost"
 git config user.name "bootstrap"
@@ -78,14 +82,23 @@ git am ${build_dir}/SVT-HEVC/ffmpeg_plugin/${patch}
 patch=0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
 git am ${build_dir}/SVT-AV1/ffmpeg_plugin/${patch}
 
-export PKG_CONFIG_PATH=${install_dir}/lib/pkgconfig:${PKG_CONFIG_PATH}
+sed -i 's/OBJS-$(CONFIG_TESTSRC2_FILTER)               += vsrc_testsrc.o/OBJS-$(CONFIG_TESTSRC2_FILTER)               += vsrc_testsrc.o ..\/libavutil\/xga_font_data.o/' \
+      ./libavfilter/Makefile
 
+export PKG_CONFIG_PATH=${install_dir}/lib/pkgconfig:${PKG_CONFIG_PATH}
 echo PKG_CONFIG_PATH:${PKG_CONFIG_PATH}
+
+if [ "$1" == "gpl" ]; then
+  enable_x264options='--enable-gpl --enable-libx264 --enable-encoder=libx264'
+else
+  enable_x264options=''
+fi
+
 ./configure --disable-vaapi \
             --disable-cuda-llvm \
             --prefix=${install_dir} \
-            --disable-shared \
             --enable-static \
+            --disable-shared \
             --enable-pic  \
             --disable-network  \
             --disable-everything \
@@ -110,13 +123,17 @@ echo PKG_CONFIG_PATH:${PKG_CONFIG_PATH}
             --disable-nvenc \
             --disable-v4l2-m2m \
             --disable-videotoolbox  \
+            ${enable_x264options}  \
             --enable-indev=lavfi \
             --enable-protocol=file  \
             --enable-bsf=h264_mp4toannexb \
             --enable-bsf=hevc_mp4toannexb  \
+            --enable-bsf=mjpeg2jpeg  \
+            --enable-bsf=mjpega_dump_header  \
             --enable-decoder=rawvideo \
             --enable-encoder=rawvideo \
             --enable-demuxer=rawvideo  \
+            --enable-demuxer=mjpeg  \
             --enable-muxer=rawvideo  \
             --enable-muxer=null \
             --enable-decoder=wrapped_avframe \
@@ -126,8 +143,10 @@ echo PKG_CONFIG_PATH:${PKG_CONFIG_PATH}
             --enable-muxer=mjpeg  \
             --enable-muxer=hevc \
             --enable-muxer=ivf \
+            --enable-muxer=image2   \
+            --enable-demuxer=image2  \
             --enable-filter=testsrc  \
-            --enable-filter=testsrc2 \
+            --enable-filter=testsrc2  \
             --enable-filter=rgbtestsrc  \
             --enable-filter=yuvtestsrc \
             --enable-demuxer=h264  \
@@ -138,13 +157,20 @@ echo PKG_CONFIG_PATH:${PKG_CONFIG_PATH}
             --enable-parser=hevc  \
             --enable-demuxer=ivf \
             --enable-parser=av1  \
+            --enable-parser=mjpeg  \
             --enable-decoder=mpeg2video \
             --enable-encoder=mpeg2video  \
             --enable-decoder=mjpeg \
             --enable-encoder=mjpeg  \
             --enable-filter=scale \
+            --enable-filter=crop   \
+            --enable-filter=overlay   \
+            --enable-filter=split   \
+            --enable-filter=drawbox   \
             --enable-filter=psnr \
             --enable-filter=ssim  \
+            --enable-filter=select \
+            --enable-filter=concat \
             --enable-libsvthevc \
             --enable-encoder=libsvt_hevc \
             --enable-libsvtav1 \
diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -8,18 +8,51 @@
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 proj_dir="$( dirname "${script_dir}" )"
 cd ${proj_dir}
-set -o errexit
+##set -o errexit
 ## start of commands -----------------------------------------------------------
-source test/tools/env/vars.sh
+## capture ci errors that should not block the rest of the chain
+ci_error=0
+
 script/lint
-if [ -z "$VPL_BUILD_DEPENDENCIES" ];then
-    source script/bootstrap
+if [ $? -ne 0 ];then
+    echo "--- Linting FAILED ---"
+    ci_error=1
 fi
-script/package
+
+if [ -z "$VPL_BUILD_DEPENDENCIES" ];then
+    if [ "$1" == "gpl" ]; then
+      source script/bootstrap gpl
+    else
+      source script/bootstrap
+    fi
+    if [ $? -ne 0 ];then
+        echo "--- Bootstrapping FAILED---"
+        exit 1
+    fi
+fi
+
+if [ "$1" == "gpl" ]; then
+  source script/package gpl
+else 
+  source script/package
+fi
+if [ $? -ne 0 ];then
+    echo "--- Packaging FAILED---"
+    exit 1
+fi
 
 # run smoke tests
-pushd _build
 ${proj_dir}/script/test
-popd
-echo --- All Smoke Tests PASSED ---
+if [ $? -ne 0 ];then
+    echo "--- Smoke Tests FAILED ---"
+    ci_error=1
+fi
+
+if [ $ci_error -ne 0 ]; then
+    echo "--- CI testing FAILED ---"
+    exit 1
+else
+    echo "---All Tests PASSED ---"
+    exit 0
+fi
 
