Make scripts more robust and flexible (#276)
* Make scripts more robust and flexible

* Update README.md

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -6,7 +6,8 @@
 ###############################################################################
 # Build base dependencies.
 
-set -o errexit
+# Do not set Exit on Error in scripts that will be sourced
+# set -o errexit
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
@@ -17,9 +18,28 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --desc "Build base dependencies." \
     -- "$@"
 
-pushd "${PROJ_DIR}"
-  python3 -m venv _build-venv
-  . _build-venv/bin/activate
-  python -m pip install -r "${PROJ_DIR}/requirements.txt"
-  export pybind11_DIR="$(python -m pybind11 --cmakedir)"
-popd
+###############################################################################
+# Globals
+if [ -z "${VPL_DISP_PY_VENV}" ]
+then
+  VPL_DISP_PY_VENV="${PROJ_DIR}/_build-venv"
+fi
+
+if [ -z "${VPL_DISP_PY_VENV_VER}" ]
+then
+  VPL_DISP_PY_VENV_VER=3
+fi
+###############################################################################
+
+python${VPL_DISP_PY_VENV_VER} -m venv "${VPL_DISP_PY_VENV}"
+
+# there are sometimes issues with creating the venv. seems to be
+# related to the folder being called "venv" rerunning seems to resolve it.
+if [ ! -f "${VPL_DISP_PY_VENV}/bin/activate" ]
+then
+  python${VPL_DISP_PY_VENV_VER} -m venv "${VPL_DISP_PY_VENV}"
+fi
+
+. "${VPL_DISP_PY_VENV}/bin/activate"
+python -m pip install -r "${PROJ_DIR}/requirements.txt"
+export pybind11_DIR="$(python -m pybind11 --cmakedir)"
diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -6,7 +6,12 @@
 ###############################################################################
 # Build base.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
@@ -16,6 +21,14 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --name build \
     --desc "Build base." \
     -- "$@"
+
+###############################################################################
+# Globals
+if [ -z "${VPL_DISP_BUILD_DIR}" ]
+then
+  VPL_DISP_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
 
 if [ -n "${BOOTSTRAP_OPT}" ]
 then
@@ -31,20 +44,18 @@ fi
 
 COFIG_CM_OPT="-DCMAKE_BUILD_TYPE=${COFIG_OPT}"
 
-pushd "${PROJ_DIR}"
-  BUILD_DIR=_build
-  if [ "${WARNING_AS_ERROR_OPT}" == "yes" ]; then
-    CMAKE_WARN_OPTS=-DENABLE_WARNING_AS_ERROR=ON
-  fi
-  mkdir -p "${BUILD_DIR}"
-  pushd "${BUILD_DIR}"
-    cmake "${INSTALL_PREFIX_CM_OPT}" ${CMAKE_WARN_OPTS} "${COFIG_CM_OPT}" -DBUILD_PYTHON_BINDING=1 -DBUILD_TESTS=ON "${PROJ_DIR}"
-    make -j "$(nproc)" VERBOSE=1
-    cmake --build . --config "${COFIG_OPT}" --target package
-  popd
+BUILD_DIR="${VPL_DISP_BUILD_DIR}"
+if [ "${WARNING_AS_ERROR_OPT}" == "yes" ]; then
+  CMAKE_WARN_OPTS=-DENABLE_WARNING_AS_ERROR=ON
+fi
+mkdir -p "${BUILD_DIR}"
+pushd "${BUILD_DIR}"
+  cmake "${INSTALL_PREFIX_CM_OPT}" ${CMAKE_WARN_OPTS} "${COFIG_CM_OPT}" -DBUILD_PYTHON_BINDING=1 -DBUILD_TESTS=ON "${PROJ_DIR}"
+  make -j "$(nproc)" VERBOSE=1
+  cmake --build . --config "${COFIG_OPT}" --target package
 popd
 
 # Signal to CI system
 if [ -n "${TEAMCITY_VERSION}" ]; then
-  echo "##teamcity[publishArtifacts 'oneVPL/${BUILD_DIR}/*-all.zip=>']"
+  echo "##teamcity[publishArtifacts '${BUILD_DIR}/*-all.zip=>']"
 fi
diff --git a/script/buildall b/script/buildall
--- a/script/buildall
+++ b/script/buildall
@@ -6,7 +6,12 @@
 ###############################################################################
 # Unified Build (Depricated, use e2e build).
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 # Set script folder
diff --git a/script/clean b/script/clean
--- a/script/clean
+++ b/script/clean
@@ -6,7 +6,12 @@
 ###############################################################################
 # Clean base.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
@@ -17,29 +22,16 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --desc "Clean base." \
     -- "$@"
 
-if [ -n "${BOOTSTRAP_OPT}" ]
+###############################################################################
+# Globals
+if [ -z "${VPL_DISP_BUILD_DIR}" ]
 then
-  if [ -e "${VPL_BUILD_DEPENDENCIES}" ]
-  then
-      echo "Cleaning dependencies cache folder..."
-      rm -rf "${VPL_BUILD_DEPENDENCIES}"
-  fi
+  VPL_DISP_BUILD_DIR="${PROJ_DIR}/_build"
 fi
+###############################################################################
 
-pushd "${PROJ_DIR}"
-  if [ -e _deps ]
-  then
-      echo "Cleaning base dependencies folder..."
-      rm -rf _build
-  fi
-  if [ -e _extbuild ]
-  then
-      echo "Cleaning base dependencies build folder..."
-      rm -rf _extbuild
-  fi
-  if [ -e _build ]
-  then
-      echo "Cleaning base build folder..."
-      rm -rf _build
-  fi
-popd
+if [ -e "${VPL_DISP_BUILD_DIR}" ]
+then
+    echo "Cleaning base build folder..."
+    rm -rf "${VPL_DISP_BUILD_DIR}"
+fi
diff --git a/script/cleanall b/script/cleanall
--- a/script/cleanall
+++ b/script/cleanall
@@ -7,7 +7,12 @@
 # Unified Clean (Depricated, use e2e clean).
 
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 # Set script folder
diff --git a/script/e2e/clean b/script/e2e/clean
--- a/script/e2e/clean
+++ b/script/e2e/clean
@@ -6,7 +6,12 @@
 ###############################################################################
 # Clean project.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -6,7 +6,12 @@
 ###############################################################################
 # Check code for issues.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 # Set script folder
diff --git a/script/stress b/script/stress
--- a/script/stress
+++ b/script/stress
@@ -22,7 +22,21 @@
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 proj_dir="$( dirname "${script_dir}" )"
 cd ${proj_dir}
-set -o errexit
+
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
+
+###############################################################################
+# Globals
+if [ -z "${VPL_DISP_BUILD_DIR}" ]
+then
+  VPL_DISP_BUILD_DIR="${proj_dir}/_build"
+fi
+###############################################################################
 
 if [ "$1" == "" ];then
      NUM_ITERATION=1
@@ -35,14 +49,14 @@ echo
 
 ## start of commands -----------------------------------------------------------
 source ${proj_dir}/test/tools/env/vars.sh
-if [ -n "${VPL_BUILD_DEPENDENCIES}" ]; then
+if [ -z "${VPL_BUILD_DEPENDENCIES}" ]; then
     export ffmpeg_dir=${VPL_BUILD_DEPENDENCIES}/bin
 else
     echo "VPL_BUILD_DEPENDENCIES not defined. Did you run bootstrap?"
     exit 1
 fi
 export PATH=${ffmpeg_dir}:${PATH}
-work_dir=${proj_dir}/_build
+work_dir=${VPL_DISP_BUILD_DIR}
 
 cd ${work_dir}
 export LD_LIBRARY_PATH=$PWD
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -6,23 +6,34 @@
 ###############################################################################
 # Run basic tests on base.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
-# Set script folder
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
 
-# Set root folder
-PROJ_DIR="$( dirname "${SCRIPT_DIR}" )"
+# Read command line options
+. "${SCRIPT_DIR}/_buildopts.sh" \
+    --name test \
+    --desc "Run basic tests on base." \
+    -- "$@"
 
-result_all=0
+###############################################################################
+# Globals
+if [ -z "${VPL_DISP_BUILD_DIR}" ]
+then
+  VPL_DISP_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
 
-pushd "${PROJ_DIR}"
-  BUILD_DIR=_build
-  pushd "${BUILD_DIR}"
-    ctest  --config "${COFIG_OPT}"
-    result_all=$?
-  popd
+BUILD_DIR="${VPL_DISP_BUILD_DIR}"
+pushd "${BUILD_DIR}"
+  ctest  --config "${COFIG_OPT}"
+  result_all=$?
 popd
 
 exit $result_all
